### ISSUE TITLE
Version tag

### ISSUE THREAD

**Issue by brad-intel** [connorimes/SPECjvm2008#2]
I know this is a legacy benchmark but, for completion sake, could you add a version tag to the repo? No particular format (but something like v1.0.0 would be nice)

**Comment by connorimes** [comment]
I don't see that creating a tag makes anything here more complete, and in fact might be misleading b/c they would be pretty arbitrary.  Are you trying to do something that you think you need a git tag for?  You can always refer to a specific commit hash, which has the same effect.

The reason I created this repo in the first place was to have a way to modify the source for different project experiments and track those changes.  IIRC, I just took the vanilla source, added it to a git repo, and made a couple of commits on top of it for convenience, then created branches from there.

**Comment by brad-intel** [comment]
> I don't see that creating a tag makes anything here more complete, and in fact might be misleading b/c they would be pretty arbitrary. Are you trying to do something that you think you need a git tag for? You can always refer to a specific commit hash, which has the same effect.
> 
> The reason I created this repo in the first place was to have a way to modify the source for different project experiments and track those changes. IIRC, I just took the vanilla source, added it to a git repo, and made a couple of commits on top of it for convenience, then created branches from there.

When benchmarking we need repeatability. Most repositories are tagging their releases and that makes it easier to get used in a CI/CD environment. Of course the commit ID is achieving the same (minus readability: one does not know what version that tag is just by reading the CI/CD build instructions). 

It was just a suggestion, of course you do whatever you see fit.

**Comment by connorimes** [comment]
I appreciate the suggestion.  However, because this is not an official repository, I feel it's best not to create an arbitrary version tag.  You can always fork the repo and create a tag in your own fork though, then point your CI/CD pipeline there.

Cheers.
